name: pytest
on: push, workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest
        run: pytest -v
